In [1]:
import pandas as pd

In [2]:
# Series
data = [10, 20, 30, 40, 50]
series = pd.Series(data)
print("Pandas Series:\n", series)

Pandas Series:
 0    10
1    20
2    30
3    40
4    50
dtype: int64

In [4]:
data = [10,20,30,40,50]
index = ['a','b','c','d','e']
series = pd.Series(data,index=index)
print("\nPandas Series with custom index:\n", series)

Pandas Series with custom index:
 a    10
b    20
c    30
d    40
e    50
dtype: int64

In [5]:
## DataFrame
data = pd.DataFrame(pd.read_csv('Online Sales Data.csv'))
data

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [15]:
data.loc[4:]

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
5,10006,2024-01-06,Sports,Wilson Evolution Basketball,5,29.99,149.95,Asia,Credit Card
6,10007,2024-01-07,Electronics,MacBook Pro 16-inch,1,2499.99,2499.99,North America,Credit Card
7,10008,2024-01-08,Home Appliances,Blueair Classic 480i,2,599.99,1199.98,Europe,PayPal
8,10009,2024-01-09,Clothing,Nike Air Force 1,6,89.99,539.94,Asia,Debit Card
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [16]:
data.iloc[2:5]

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [20]:
data.head()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [21]:
data.iloc[0]

Transaction ID              10001
Date                   2024-01-01
Product Category      Electronics
Product Name        iPhone 14 Pro
Units Sold                      2
Unit Price                 999.99
Total Revenue             1999.98
Region              North America
Payment Method        Credit Card
Name: 0, dtype: object

In [29]:
data.at[2,'Product Name']

"Levi's 501 Jeans"

In [26]:
data.iat[1, 2]

'Home Appliances'

In [31]:
# Data Manupulation Examples
df = data.copy()

In [33]:
df.head()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [34]:
df = df.drop(['Total Revenue'],axis=1)

In [35]:
df.head()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,Europe,PayPal

In [40]:
df['TotalSales'] = df['Units Sold'] * df['Unit Price']

In [41]:
df.head()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Region,Payment Method,TotalSales
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,North America,Credit Card,1999.98
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,Europe,PayPal,499.99
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,Asia,Debit Card,209.97
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,North America,Credit Card,63.96
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,Europe,PayPal,89.99

In [42]:
df.dtypes

Transaction ID        int64
Date                 object
Product Category     object
Product Name         object
Units Sold            int64
Unit Price          float64
Region               object
Payment Method       object
TotalSales          float64
dtype: object

In [43]:
df.describe()

       Transaction ID  Units Sold   Unit Price   TotalSales
count       240.00000  240.000000   240.000000   240.000000
mean      10120.50000    2.158333   236.395583   335.699375
std          69.42622    1.322454   429.446695   485.804469
min       10001.00000    1.000000     6.500000     6.500000
25%       10060.75000    1.000000    29.500000    62.965000
50%       10120.50000    2.000000    89.990000   179.970000
75%       10180.25000    3.000000   249.990000   399.225000
max       10240.00000   10.000000  3899.990000  3899.990000

In [53]:
grouped = df.groupby('Payment Method')['TotalSales'].sum()
print("Grouped DataFrame by Payment Method:\n", grouped)

Grouped DataFrame by Payment Method:
 Payment Method
Credit Card    51170.86
Debit Card      8128.93
PayPal         21268.06
Name: TotalSales, dtype: float64

In [56]:
print(grouped.sum())

80567.85

In [51]:
print(df['TotalSales'].sum())

80567.84999999999